#!/bin/bash

# Fluttering Pebble — pre-1985 contamination-controlled training pipeline.
#
# Trains a small LLM on a corpus of pre-1929 books + pre-1985 PubMed abstracts,
# then SFTs it on synthetic data generated by a local LLM and filtered by Claude.
# Goal: probe whether a bounded-knowledge LLM can come up with novel-to-1985
# scientific ideas.
#
# Required environment (pick one Anthropic backend):
#   Option A — public Anthropic API:
#       ANTHROPIC_API_KEY        Claude API key
#   Option B — Google Cloud Vertex AI:
#       ANTHROPIC_BACKEND=vertex
#       ANTHROPIC_VERTEX_PROJECT_ID  GCP project id
#       ANTHROPIC_VERTEX_REGION      e.g. us-east5
#       (auth: gcloud auth application-default login OR GOOGLE_APPLICATION_CREDENTIALS)
#       Optional ID overrides: ANTHROPIC_HAIKU_MODEL, ANTHROPIC_SONNET_MODEL
#
# Local LLM for bulk SFT generation:
#   OPENAI_BASE_URL    — local OpenAI-compatible LLM endpoint (e.g. http://localhost:8000/v1)
#   LOCAL_LLM_MODEL    — model name the local server exposes (e.g. Qwen/Qwen3-32B-Instruct)
#
# Optional environment:
#   DEPTH              — model depth (default 24); pick smaller if you have less compute
#   WANDB_RUN          — wandb run name (default 'dummy', skips wandb)
#   GROUNDED_QA_N, CODE_N, TOOL_USE_N, COMPREHENSION_N — SFT category targets
#   TARGET_TOKENS      — pretraining corpus size in tokens (default 30B)
#
# Resumability: every step is resumable. Kill at any point and re-run.

set -e

export OMP_NUM_THREADS=1
export NANOCHAT_BASE_DIR="${NANOCHAT_BASE_DIR:-$HOME/.cache/nanochat}"
export NANOCHAT_DATASET="pre1985"   # IMPORTANT: switches dataset.py to pre-1985
mkdir -p "$NANOCHAT_BASE_DIR"

# venv setup
command -v uv &> /dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
[ -d ".venv" ] || uv venv
uv sync --extra gpu
source .venv/bin/activate

# Defaults
DEPTH="${DEPTH:-24}"
WANDB_RUN="${WANDB_RUN:-dummy}"
GROUNDED_QA_N="${GROUNDED_QA_N:-20000}"
CODE_N="${CODE_N:-10000}"
TOOL_USE_N="${TOOL_USE_N:-5000}"
COMPREHENSION_N="${COMPREHENSION_N:-5000}"
TARGET_TOKENS="${TARGET_TOKENS:-30000000000}"

if [ "${ANTHROPIC_BACKEND:-api}" = "vertex" ]; then
    if [ -z "$ANTHROPIC_VERTEX_PROJECT_ID" ]; then
        echo "ERROR: ANTHROPIC_BACKEND=vertex requires ANTHROPIC_VERTEX_PROJECT_ID."
        exit 1
    fi
    echo "Anthropic backend: Vertex (project=$ANTHROPIC_VERTEX_PROJECT_ID region=${ANTHROPIC_VERTEX_REGION:-unset})"
elif [ -z "$ANTHROPIC_API_KEY" ]; then
    echo "ERROR: ANTHROPIC_API_KEY is not set (or set ANTHROPIC_BACKEND=vertex with project/region)."
    exit 1
else
    echo "Anthropic backend: public API"
fi
if [ -z "$OPENAI_BASE_URL" ]; then
    echo "WARNING: OPENAI_BASE_URL is not set. SFT data generation will use http://localhost:8000/v1"
fi

python -m nanochat.report reset

# -----------------------------------------------------------------------------
# 1) Build pre-1985 pretraining corpus (CPU, multi-hour, idempotent)
echo "=========================================================================="
echo "1) Building pre-1985 pretraining corpus (target ~${TARGET_TOKENS} tokens)"
echo "=========================================================================="
python -m scripts.build_pretrain_corpus \
    --target-tokens "$TARGET_TOKENS" \
    --mix "books_ia:0.55,books_loc:0.10,books_gutenberg:0.05,pubmed:0.30"

# -----------------------------------------------------------------------------
# 2) Train tokenizer on the new corpus
echo "=========================================================================="
echo "2) Training tokenizer on pre-1985 corpus"
echo "=========================================================================="
python -m scripts.tok_train
python -m scripts.tok_eval

# -----------------------------------------------------------------------------
# 3) Pretrain (uses unmodified base_train.py — picks up corpus via NANOCHAT_DATASET)
echo "=========================================================================="
echo "3) Pretraining (depth=$DEPTH)"
echo "=========================================================================="
torchrun --standalone --nproc_per_node=8 -m scripts.base_train -- \
    --depth="$DEPTH" \
    --device-batch-size=16 \
    --fp8 \
    --run="$WANDB_RUN"

torchrun --standalone --nproc_per_node=8 -m scripts.base_eval -- --device-batch-size=16

# -----------------------------------------------------------------------------
# 4) Generate identity conversations (~$5 in Claude calls, ~30 min)
echo "=========================================================================="
echo "4) Generating identity conversations"
echo "=========================================================================="
python -m dev.gen_identity_pre1985 --num=200 --workers=8

# -----------------------------------------------------------------------------
# 5) Generate bulk SFT data (local LLM, ~hours; Claude filter ~\$60-100, resumable)
echo "=========================================================================="
echo "5) Generating SFT data (resumable; ~hours of local LLM calls)"
echo "=========================================================================="
python -m scripts.build_sft_data \
    --grounded-qa "$GROUNDED_QA_N" \
    --code "$CODE_N" \
    --tool-use "$TOOL_USE_N" \
    --comprehension "$COMPREHENSION_N" \
    --workers 16

# -----------------------------------------------------------------------------
# 6) SFT
echo "=========================================================================="
echo "6) Supervised fine-tuning"
echo "=========================================================================="
torchrun --standalone --nproc_per_node=8 -m scripts.chat_sft_pre1985 -- \
    --device-batch-size=16 \
    --chatcore-every=-1 \
    --run="$WANDB_RUN"

# -----------------------------------------------------------------------------
# Done. Try it out:
echo "=========================================================================="
echo "Done. Try chatting with Fluttering Pebble:"
echo "  python -m scripts.chat_cli"
echo "  python -m scripts.chat_web    (browser UI)"
echo "=========================================================================="

python -m nanochat.report generate
